#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 134
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 32
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 67

enum ts_symbol_identifiers {
  sym_IDENT = 1,
  anon_sym_SEMI = 2,
  anon_sym_within = 3,
  anon_sym_block = 4,
  anon_sym_class = 5,
  anon_sym_model = 6,
  anon_sym_package = 7,
  anon_sym_end = 8,
  anon_sym_extends = 9,
  anon_sym_COMMA = 10,
  anon_sym_EQ = 11,
  anon_sym_COLON_EQ = 12,
  anon_sym_break = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_in = 16,
  anon_sym_not = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_false = 20,
  anon_sym_true = 21,
  anon_sym_LBRACE = 22,
  anon_sym_for = 23,
  anon_sym_RBRACE = 24,
  anon_sym_DOT = 25,
  anon_sym_annotation = 26,
  sym_BOM = 27,
  sym_STRING = 28,
  sym_UNSIGNED_INTEGER = 29,
  sym_UNSIGNED_REAL = 30,
  sym_COMMENT = 31,
  sym_storedDefinition = 32,
  sym_withinClause = 33,
  sym_classDefinition = 34,
  sym_classPrefixes = 35,
  sym__classSpecifier = 36,
  sym_longClassSpecifier = 37,
  sym_elementList = 38,
  sym__element = 39,
  sym_namedElement = 40,
  sym_extendsClause = 41,
  sym_componentClause = 42,
  sym_componentDeclaration = 43,
  sym_modification = 44,
  sym_modificationExpression = 45,
  sym_classModification = 46,
  sym__argument = 47,
  sym_elementModification = 48,
  sym_forIndex = 49,
  sym__expression = 50,
  sym__simpleExpression = 51,
  sym_unaryExpression = 52,
  sym_binaryExpression = 53,
  sym__primaryExpression = 54,
  sym__literal = 55,
  sym__unsignedNumberLiteral = 56,
  sym_unsignedIntegerLiteral = 57,
  sym_unsignedRealLiteral = 58,
  sym_stringLiteral = 59,
  sym_logicalLiteral = 60,
  sym_arrayConstructor = 61,
  sym_typeSpecifier = 62,
  sym_name = 63,
  sym_descriptionString = 64,
  sym_annotationClause = 65,
  aux_sym_storedDefinition_repeat1 = 66,
  aux_sym_elementList_repeat1 = 67,
  aux_sym_componentClause_repeat1 = 68,
  aux_sym_classModification_repeat1 = 69,
  aux_sym_arrayConstructor_repeat1 = 70,
  aux_sym_arrayConstructor_repeat2 = 71,
  aux_sym_descriptionString_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_IDENT] = "IDENT",
  [anon_sym_SEMI] = ";",
  [anon_sym_within] = "within",
  [anon_sym_block] = "block",
  [anon_sym_class] = "class",
  [anon_sym_model] = "model",
  [anon_sym_package] = "package",
  [anon_sym_end] = "end",
  [anon_sym_extends] = "extends",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_break] = "break",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_in] = "in",
  [anon_sym_not] = "not",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_false] = "false",
  [anon_sym_true] = "true",
  [anon_sym_LBRACE] = "{",
  [anon_sym_for] = "for",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [anon_sym_annotation] = "annotation",
  [sym_BOM] = "BOM",
  [sym_STRING] = "STRING",
  [sym_UNSIGNED_INTEGER] = "UNSIGNED_INTEGER",
  [sym_UNSIGNED_REAL] = "UNSIGNED_REAL",
  [sym_COMMENT] = "COMMENT",
  [sym_storedDefinition] = "storedDefinition",
  [sym_withinClause] = "withinClause",
  [sym_classDefinition] = "classDefinition",
  [sym_classPrefixes] = "classPrefixes",
  [sym__classSpecifier] = "_classSpecifier",
  [sym_longClassSpecifier] = "longClassSpecifier",
  [sym_elementList] = "elementList",
  [sym__element] = "_element",
  [sym_namedElement] = "namedElement",
  [sym_extendsClause] = "extendsClause",
  [sym_componentClause] = "componentClause",
  [sym_componentDeclaration] = "componentDeclaration",
  [sym_modification] = "modification",
  [sym_modificationExpression] = "modificationExpression",
  [sym_classModification] = "classModification",
  [sym__argument] = "_argument",
  [sym_elementModification] = "elementModification",
  [sym_forIndex] = "forIndex",
  [sym__expression] = "_expression",
  [sym__simpleExpression] = "_simpleExpression",
  [sym_unaryExpression] = "unaryExpression",
  [sym_binaryExpression] = "binaryExpression",
  [sym__primaryExpression] = "_primaryExpression",
  [sym__literal] = "_literal",
  [sym__unsignedNumberLiteral] = "_unsignedNumberLiteral",
  [sym_unsignedIntegerLiteral] = "unsignedIntegerLiteral",
  [sym_unsignedRealLiteral] = "unsignedRealLiteral",
  [sym_stringLiteral] = "stringLiteral",
  [sym_logicalLiteral] = "logicalLiteral",
  [sym_arrayConstructor] = "arrayConstructor",
  [sym_typeSpecifier] = "typeSpecifier",
  [sym_name] = "name",
  [sym_descriptionString] = "descriptionString",
  [sym_annotationClause] = "annotationClause",
  [aux_sym_storedDefinition_repeat1] = "storedDefinition_repeat1",
  [aux_sym_elementList_repeat1] = "elementList_repeat1",
  [aux_sym_componentClause_repeat1] = "componentClause_repeat1",
  [aux_sym_classModification_repeat1] = "classModification_repeat1",
  [aux_sym_arrayConstructor_repeat1] = "arrayConstructor_repeat1",
  [aux_sym_arrayConstructor_repeat2] = "arrayConstructor_repeat2",
  [aux_sym_descriptionString_repeat1] = "descriptionString_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_IDENT] = sym_IDENT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_within] = anon_sym_within,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_annotation] = anon_sym_annotation,
  [sym_BOM] = sym_BOM,
  [sym_STRING] = sym_STRING,
  [sym_UNSIGNED_INTEGER] = sym_UNSIGNED_INTEGER,
  [sym_UNSIGNED_REAL] = sym_UNSIGNED_REAL,
  [sym_COMMENT] = sym_COMMENT,
  [sym_storedDefinition] = sym_storedDefinition,
  [sym_withinClause] = sym_withinClause,
  [sym_classDefinition] = sym_classDefinition,
  [sym_classPrefixes] = sym_classPrefixes,
  [sym__classSpecifier] = sym__classSpecifier,
  [sym_longClassSpecifier] = sym_longClassSpecifier,
  [sym_elementList] = sym_elementList,
  [sym__element] = sym__element,
  [sym_namedElement] = sym_namedElement,
  [sym_extendsClause] = sym_extendsClause,
  [sym_componentClause] = sym_componentClause,
  [sym_componentDeclaration] = sym_componentDeclaration,
  [sym_modification] = sym_modification,
  [sym_modificationExpression] = sym_modificationExpression,
  [sym_classModification] = sym_classModification,
  [sym__argument] = sym__argument,
  [sym_elementModification] = sym_elementModification,
  [sym_forIndex] = sym_forIndex,
  [sym__expression] = sym__expression,
  [sym__simpleExpression] = sym__simpleExpression,
  [sym_unaryExpression] = sym_unaryExpression,
  [sym_binaryExpression] = sym_binaryExpression,
  [sym__primaryExpression] = sym__primaryExpression,
  [sym__literal] = sym__literal,
  [sym__unsignedNumberLiteral] = sym__unsignedNumberLiteral,
  [sym_unsignedIntegerLiteral] = sym_unsignedIntegerLiteral,
  [sym_unsignedRealLiteral] = sym_unsignedRealLiteral,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym_logicalLiteral] = sym_logicalLiteral,
  [sym_arrayConstructor] = sym_arrayConstructor,
  [sym_typeSpecifier] = sym_typeSpecifier,
  [sym_name] = sym_name,
  [sym_descriptionString] = sym_descriptionString,
  [sym_annotationClause] = sym_annotationClause,
  [aux_sym_storedDefinition_repeat1] = aux_sym_storedDefinition_repeat1,
  [aux_sym_elementList_repeat1] = aux_sym_elementList_repeat1,
  [aux_sym_componentClause_repeat1] = aux_sym_componentClause_repeat1,
  [aux_sym_classModification_repeat1] = aux_sym_classModification_repeat1,
  [aux_sym_arrayConstructor_repeat1] = aux_sym_arrayConstructor_repeat1,
  [aux_sym_arrayConstructor_repeat2] = aux_sym_arrayConstructor_repeat2,
  [aux_sym_descriptionString_repeat1] = aux_sym_descriptionString_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_IDENT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_within] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_annotation] = {
    .visible = true,
    .named = false,
  },
  [sym_BOM] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING] = {
    .visible = true,
    .named = true,
  },
  [sym_UNSIGNED_INTEGER] = {
    .visible = true,
    .named = true,
  },
  [sym_UNSIGNED_REAL] = {
    .visible = true,
    .named = true,
  },
  [sym_COMMENT] = {
    .visible = true,
    .named = true,
  },
  [sym_storedDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_withinClause] = {
    .visible = true,
    .named = true,
  },
  [sym_classDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_classPrefixes] = {
    .visible = true,
    .named = true,
  },
  [sym__classSpecifier] = {
    .visible = false,
    .named = true,
  },
  [sym_longClassSpecifier] = {
    .visible = true,
    .named = true,
  },
  [sym_elementList] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_namedElement] = {
    .visible = true,
    .named = true,
  },
  [sym_extendsClause] = {
    .visible = true,
    .named = true,
  },
  [sym_componentClause] = {
    .visible = true,
    .named = true,
  },
  [sym_componentDeclaration] = {
    .visible = true,
    .named = true,
  },
  [sym_modification] = {
    .visible = true,
    .named = true,
  },
  [sym_modificationExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_classModification] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_elementModification] = {
    .visible = true,
    .named = true,
  },
  [sym_forIndex] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simpleExpression] = {
    .visible = false,
    .named = true,
  },
  [sym_unaryExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_binaryExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__primaryExpression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym__unsignedNumberLiteral] = {
    .visible = false,
    .named = true,
  },
  [sym_unsignedIntegerLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_unsignedRealLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_logicalLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_arrayConstructor] = {
    .visible = true,
    .named = true,
  },
  [sym_typeSpecifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_descriptionString] = {
    .visible = true,
    .named = true,
  },
  [sym_annotationClause] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_storedDefinition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_elementList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_componentClause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_classModification_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arrayConstructor_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arrayConstructor_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_descriptionString_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotationClause = 1,
  field_argument = 2,
  field_block = 3,
  field_class = 4,
  field_classDefinition = 5,
  field_classModification = 6,
  field_classPrefixes = 7,
  field_classSpecifier = 8,
  field_componentClause = 9,
  field_componentDeclaration = 10,
  field_descriptionString = 11,
  field_element = 12,
  field_elementList = 13,
  field_endIdentifier = 14,
  field_expression = 15,
  field_forIndex = 16,
  field_global = 17,
  field_identifier = 18,
  field_model = 19,
  field_modification = 20,
  field_modificationExpression = 21,
  field_name = 22,
  field_operand = 23,
  field_operand1 = 24,
  field_operand2 = 25,
  field_operator = 26,
  field_package = 27,
  field_packagePrefixName = 28,
  field_qualifier = 29,
  field_typeSpecifier = 30,
  field_value = 31,
  field_withinClause = 32,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotationClause] = "annotationClause",
  [field_argument] = "argument",
  [field_block] = "block",
  [field_class] = "class",
  [field_classDefinition] = "classDefinition",
  [field_classModification] = "classModification",
  [field_classPrefixes] = "classPrefixes",
  [field_classSpecifier] = "classSpecifier",
  [field_componentClause] = "componentClause",
  [field_componentDeclaration] = "componentDeclaration",
  [field_descriptionString] = "descriptionString",
  [field_element] = "element",
  [field_elementList] = "elementList",
  [field_endIdentifier] = "endIdentifier",
  [field_expression] = "expression",
  [field_forIndex] = "forIndex",
  [field_global] = "global",
  [field_identifier] = "identifier",
  [field_model] = "model",
  [field_modification] = "modification",
  [field_modificationExpression] = "modificationExpression",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operand1] = "operand1",
  [field_operand2] = "operand2",
  [field_operator] = "operator",
  [field_package] = "package",
  [field_packagePrefixName] = "packagePrefixName",
  [field_qualifier] = "qualifier",
  [field_typeSpecifier] = "typeSpecifier",
  [field_value] = "value",
  [field_withinClause] = "withinClause",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 1},
  [9] = {.index = 8, .length = 1},
  [10] = {.index = 9, .length = 2},
  [11] = {.index = 11, .length = 1},
  [12] = {.index = 12, .length = 2},
  [13] = {.index = 14, .length = 2},
  [14] = {.index = 16, .length = 1},
  [15] = {.index = 17, .length = 2},
  [16] = {.index = 19, .length = 1},
  [17] = {.index = 20, .length = 1},
  [18] = {.index = 21, .length = 1},
  [19] = {.index = 22, .length = 1},
  [20] = {.index = 23, .length = 2},
  [21] = {.index = 25, .length = 2},
  [22] = {.index = 27, .length = 1},
  [23] = {.index = 28, .length = 2},
  [24] = {.index = 30, .length = 1},
  [25] = {.index = 31, .length = 2},
  [26] = {.index = 33, .length = 1},
  [27] = {.index = 34, .length = 2},
  [28] = {.index = 36, .length = 2},
  [29] = {.index = 38, .length = 1},
  [30] = {.index = 39, .length = 2},
  [31] = {.index = 41, .length = 3},
  [32] = {.index = 44, .length = 2},
  [33] = {.index = 46, .length = 1},
  [34] = {.index = 47, .length = 2},
  [35] = {.index = 49, .length = 2},
  [36] = {.index = 51, .length = 3},
  [37] = {.index = 54, .length = 3},
  [38] = {.index = 57, .length = 1},
  [39] = {.index = 58, .length = 2},
  [40] = {.index = 60, .length = 2},
  [41] = {.index = 62, .length = 1},
  [42] = {.index = 63, .length = 1},
  [43] = {.index = 64, .length = 3},
  [44] = {.index = 67, .length = 3},
  [45] = {.index = 70, .length = 3},
  [46] = {.index = 73, .length = 1},
  [47] = {.index = 74, .length = 2},
  [48] = {.index = 76, .length = 4},
  [49] = {.index = 80, .length = 3},
  [50] = {.index = 83, .length = 2},
  [51] = {.index = 85, .length = 2},
  [52] = {.index = 87, .length = 3},
  [53] = {.index = 90, .length = 4},
  [54] = {.index = 94, .length = 2},
  [55] = {.index = 96, .length = 4},
  [56] = {.index = 100, .length = 2},
  [57] = {.index = 102, .length = 4},
  [58] = {.index = 106, .length = 1},
  [59] = {.index = 107, .length = 3},
  [60] = {.index = 110, .length = 5},
  [61] = {.index = 115, .length = 2},
  [62] = {.index = 117, .length = 2},
  [63] = {.index = 119, .length = 2},
  [64] = {.index = 121, .length = 1},
  [65] = {.index = 122, .length = 3},
  [66] = {.index = 125, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_block, 0},
  [1] =
    {field_class, 0},
  [2] =
    {field_model, 0},
  [3] =
    {field_package, 0},
  [4] =
    {field_withinClause, 0},
  [5] =
    {field_classDefinition, 0, .inherited = true},
  [6] =
    {field_identifier, 0},
  [7] =
    {field_withinClause, 1},
  [8] =
    {field_classDefinition, 1, .inherited = true},
  [9] =
    {field_classDefinition, 1, .inherited = true},
    {field_withinClause, 0},
  [11] =
    {field_classDefinition, 0},
  [12] =
    {field_classPrefixes, 0},
    {field_classSpecifier, 1},
  [14] =
    {field_classDefinition, 0, .inherited = true},
    {field_classDefinition, 1, .inherited = true},
  [16] =
    {field_packagePrefixName, 1},
  [17] =
    {field_classDefinition, 2, .inherited = true},
    {field_withinClause, 1},
  [19] =
    {field_value, 0},
  [20] =
    {field_componentClause, 0},
  [21] =
    {field_name, 0},
  [22] =
    {field_element, 0, .inherited = true},
  [23] =
    {field_identifier, 2},
    {field_qualifier, 0},
  [25] =
    {field_endIdentifier, 2},
    {field_identifier, 0},
  [27] =
    {field_typeSpecifier, 1},
  [28] =
    {field_global, 0},
    {field_name, 1},
  [30] =
    {field_classModification, 1},
  [31] =
    {field_value, 0},
    {field_value, 1, .inherited = true},
  [33] =
    {field_element, 0},
  [34] =
    {field_componentDeclaration, 1},
    {field_typeSpecifier, 0},
  [36] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
  [38] =
    {field_value, 1},
  [39] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [41] =
    {field_elementList, 1},
    {field_endIdentifier, 3},
    {field_identifier, 0},
  [44] =
    {field_identifier, 0},
    {field_modification, 1},
  [46] =
    {field_classModification, 0},
  [47] =
    {field_descriptionString, 1},
    {field_identifier, 0},
  [49] =
    {field_annotationClause, 1},
    {field_identifier, 0},
  [51] =
    {field_componentDeclaration, 1},
    {field_componentDeclaration, 2, .inherited = true},
    {field_typeSpecifier, 0},
  [54] =
    {field_descriptionString, 1},
    {field_endIdentifier, 3},
    {field_identifier, 0},
  [57] =
    {field_argument, 1},
  [58] =
    {field_modification, 1},
    {field_name, 0},
  [60] =
    {field_descriptionString, 1},
    {field_name, 0},
  [62] =
    {field_modificationExpression, 1},
  [63] =
    {field_expression, 0},
  [64] =
    {field_descriptionString, 2},
    {field_identifier, 0},
    {field_modification, 1},
  [67] =
    {field_annotationClause, 2},
    {field_identifier, 0},
    {field_modification, 1},
  [70] =
    {field_annotationClause, 2},
    {field_descriptionString, 1},
    {field_identifier, 0},
  [73] =
    {field_componentDeclaration, 1},
  [74] =
    {field_componentDeclaration, 0, .inherited = true},
    {field_componentDeclaration, 1, .inherited = true},
  [76] =
    {field_descriptionString, 1},
    {field_elementList, 2},
    {field_endIdentifier, 4},
    {field_identifier, 0},
  [80] =
    {field_annotationClause, 1},
    {field_endIdentifier, 4},
    {field_identifier, 0},
  [83] =
    {field_argument, 1},
    {field_argument, 2, .inherited = true},
  [85] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [87] =
    {field_descriptionString, 2},
    {field_modification, 1},
    {field_name, 0},
  [90] =
    {field_annotationClause, 2},
    {field_elementList, 1},
    {field_endIdentifier, 5},
    {field_identifier, 0},
  [94] =
    {field_operand, 1},
    {field_operator, 0},
  [96] =
    {field_annotationClause, 3},
    {field_descriptionString, 2},
    {field_identifier, 0},
    {field_modification, 1},
  [100] =
    {field_classModification, 0},
    {field_modificationExpression, 2},
  [102] =
    {field_annotationClause, 2},
    {field_descriptionString, 1},
    {field_endIdentifier, 5},
    {field_identifier, 0},
  [106] =
    {field_element, 1},
  [107] =
    {field_operand1, 0},
    {field_operand2, 2},
    {field_operator, 1},
  [110] =
    {field_annotationClause, 3},
    {field_descriptionString, 1},
    {field_elementList, 2},
    {field_endIdentifier, 6},
    {field_identifier, 0},
  [115] =
    {field_element, 1},
    {field_element, 2, .inherited = true},
  [117] =
    {field_element, 1},
    {field_forIndex, 3},
  [119] =
    {field_expression, 2},
    {field_identifier, 0},
  [121] =
    {field_forIndex, 1},
  [122] =
    {field_element, 1},
    {field_forIndex, 3},
    {field_forIndex, 4, .inherited = true},
  [125] =
    {field_forIndex, 0, .inherited = true},
    {field_forIndex, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 8,
        '(', 28,
        ')', 29,
        '+', 30,
        ',', 25,
        '-', 31,
        '.', 35,
        '/', 9,
        ':', 12,
        ';', 24,
        '=', 26,
      );
      if (lookahead == '\\') SKIP(22);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '}') ADVANCE(33);
      if (lookahead == 0xef) ADVANCE(14);
      if (lookahead == 0x2019) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(7);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(6);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '"', 8,
        '(', 28,
        ')', 29,
        '+', 30,
        ',', 25,
        '.', 34,
        '/', 9,
        ':', 12,
        ';', 24,
        '=', 26,
      );
      if (lookahead == '\\') SKIP(4);
      if (lookahead == 0x2019) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '\\') SKIP(2);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == 0x2019) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead == 0x2019) ADVANCE(37);
      if (lookahead == ' ' ||
          lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= '~')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == 0xbb) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 0xbf) ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 19:
      ADVANCE_MAP(
        '"', 8,
        '\'', 8,
        '?', 8,
        '\\', 8,
        'a', 8,
        'b', 8,
        'f', 8,
        'n', 8,
        'r', 8,
        't', 8,
        'v', 8,
        0x2019, 8,
      );
      END_STATE();
    case 20:
      ADVANCE_MAP(
        '"', 13,
        '\'', 13,
        '?', 13,
        '\\', 13,
        'a', 13,
        'b', 13,
        'f', 13,
        'n', 13,
        'r', 13,
        't', 13,
        'v', 13,
        0x2019, 13,
      );
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_BOM);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_IDENT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_IDENT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_STRING);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_UNSIGNED_INTEGER);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_UNSIGNED_REAL);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_UNSIGNED_REAL);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_COMMENT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_COMMENT);
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_COMMENT);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_COMMENT);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'b') ADVANCE(3);
      if (lookahead == 'c') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'm') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(9);
      if (lookahead == 'p') ADVANCE(10);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead == 'w') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(13);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 'x') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 38:
      if (lookahead == 'k') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'h') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'k') ADVANCE(52);
      END_STATE();
    case 43:
      if (lookahead == 'k') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 55:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 58:
      if (lookahead == 'g') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_within);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_annotation);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_IDENT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_within] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_annotation] = ACTIONS(1),
    [sym_BOM] = ACTIONS(1),
    [sym_STRING] = ACTIONS(1),
    [sym_UNSIGNED_INTEGER] = ACTIONS(1),
    [sym_UNSIGNED_REAL] = ACTIONS(1),
    [sym_COMMENT] = ACTIONS(3),
  },
  [1] = {
    [sym_storedDefinition] = STATE(130),
    [sym_withinClause] = STATE(26),
    [sym_classDefinition] = STATE(129),
    [sym_classPrefixes] = STATE(62),
    [aux_sym_storedDefinition_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_within] = ACTIONS(7),
    [anon_sym_block] = ACTIONS(9),
    [anon_sym_class] = ACTIONS(11),
    [anon_sym_model] = ACTIONS(13),
    [anon_sym_package] = ACTIONS(15),
    [sym_BOM] = ACTIONS(17),
    [sym_COMMENT] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(19), 1,
      anon_sym_break,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    STATE(47), 1,
      sym__expression,
    STATE(52), 1,
      sym_modificationExpression,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(33), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [47] = 11,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(19), 1,
      anon_sym_break,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    STATE(46), 1,
      sym_modificationExpression,
    STATE(47), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(33), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [94] = 21,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(33), 1,
      sym_IDENT,
    ACTIONS(35), 1,
      anon_sym_block,
    ACTIONS(37), 1,
      anon_sym_class,
    ACTIONS(39), 1,
      anon_sym_model,
    ACTIONS(41), 1,
      anon_sym_package,
    ACTIONS(43), 1,
      anon_sym_end,
    ACTIONS(45), 1,
      anon_sym_extends,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_annotation,
    ACTIONS(51), 1,
      sym_STRING,
    STATE(10), 1,
      sym_descriptionString,
    STATE(12), 1,
      aux_sym_elementList_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(72), 1,
      sym_elementList,
    STATE(76), 1,
      sym_name,
    STATE(83), 1,
      sym_typeSpecifier,
    STATE(123), 1,
      sym_annotationClause,
    STATE(124), 1,
      sym_componentClause,
    STATE(125), 1,
      sym_classDefinition,
    STATE(97), 3,
      sym__element,
      sym_namedElement,
      sym_extendsClause,
  [160] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    STATE(59), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(33), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [201] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    STATE(80), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(33), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [242] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    STATE(81), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(33), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [283] = 8,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(31), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [321] = 8,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      sym_STRING,
    ACTIONS(29), 1,
      sym_UNSIGNED_INTEGER,
    ACTIONS(31), 1,
      sym_UNSIGNED_REAL,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(21), 3,
      anon_sym_not,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(24), 11,
      sym__simpleExpression,
      sym_unaryExpression,
      sym_binaryExpression,
      sym__primaryExpression,
      sym__literal,
      sym__unsignedNumberLiteral,
      sym_unsignedIntegerLiteral,
      sym_unsignedRealLiteral,
      sym_stringLiteral,
      sym_logicalLiteral,
      sym_arrayConstructor,
  [359] = 19,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(33), 1,
      sym_IDENT,
    ACTIONS(35), 1,
      anon_sym_block,
    ACTIONS(37), 1,
      anon_sym_class,
    ACTIONS(39), 1,
      anon_sym_model,
    ACTIONS(41), 1,
      anon_sym_package,
    ACTIONS(45), 1,
      anon_sym_extends,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_annotation,
    ACTIONS(53), 1,
      anon_sym_end,
    STATE(12), 1,
      aux_sym_elementList_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(67), 1,
      sym_elementList,
    STATE(76), 1,
      sym_name,
    STATE(83), 1,
      sym_typeSpecifier,
    STATE(115), 1,
      sym_annotationClause,
    STATE(124), 1,
      sym_componentClause,
    STATE(125), 1,
      sym_classDefinition,
    STATE(97), 3,
      sym__element,
      sym_namedElement,
      sym_extendsClause,
  [419] = 16,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(55), 1,
      sym_IDENT,
    ACTIONS(58), 1,
      anon_sym_block,
    ACTIONS(61), 1,
      anon_sym_class,
    ACTIONS(64), 1,
      anon_sym_model,
    ACTIONS(67), 1,
      anon_sym_package,
    ACTIONS(72), 1,
      anon_sym_extends,
    ACTIONS(75), 1,
      anon_sym_DOT,
    STATE(11), 1,
      aux_sym_elementList_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(76), 1,
      sym_name,
    STATE(83), 1,
      sym_typeSpecifier,
    STATE(124), 1,
      sym_componentClause,
    STATE(125), 1,
      sym_classDefinition,
    ACTIONS(70), 2,
      anon_sym_end,
      anon_sym_annotation,
    STATE(97), 3,
      sym__element,
      sym_namedElement,
      sym_extendsClause,
  [471] = 16,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(33), 1,
      sym_IDENT,
    ACTIONS(35), 1,
      anon_sym_block,
    ACTIONS(37), 1,
      anon_sym_class,
    ACTIONS(39), 1,
      anon_sym_model,
    ACTIONS(41), 1,
      anon_sym_package,
    ACTIONS(45), 1,
      anon_sym_extends,
    ACTIONS(47), 1,
      anon_sym_DOT,
    STATE(11), 1,
      aux_sym_elementList_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(76), 1,
      sym_name,
    STATE(83), 1,
      sym_typeSpecifier,
    STATE(124), 1,
      sym_componentClause,
    STATE(125), 1,
      sym_classDefinition,
    ACTIONS(78), 2,
      anon_sym_end,
      anon_sym_annotation,
    STATE(97), 3,
      sym__element,
      sym_namedElement,
      sym_extendsClause,
  [523] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(84), 1,
      anon_sym_PLUS,
    STATE(13), 1,
      aux_sym_descriptionString_repeat1,
    ACTIONS(82), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
    ACTIONS(80), 8,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
      anon_sym_end,
      anon_sym_extends,
      anon_sym_annotation,
      sym_IDENT,
  [549] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(91), 1,
      anon_sym_PLUS,
    STATE(13), 1,
      aux_sym_descriptionString_repeat1,
    ACTIONS(89), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
    ACTIONS(87), 8,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
      anon_sym_end,
      anon_sym_extends,
      anon_sym_annotation,
      sym_IDENT,
  [575] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(91), 1,
      anon_sym_PLUS,
    STATE(14), 1,
      aux_sym_descriptionString_repeat1,
    ACTIONS(95), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
    ACTIONS(93), 8,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
      anon_sym_end,
      anon_sym_extends,
      anon_sym_annotation,
      sym_IDENT,
  [601] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(99), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DOT,
    ACTIONS(97), 8,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
      anon_sym_end,
      anon_sym_extends,
      anon_sym_annotation,
      sym_IDENT,
  [622] = 10,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(51), 1,
      sym_STRING,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_annotation,
    STATE(42), 1,
      sym_classModification,
    STATE(43), 1,
      sym_modification,
    STATE(58), 1,
      sym_descriptionString,
    STATE(94), 1,
      sym_annotationClause,
    ACTIONS(101), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(103), 2,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
  [655] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(51), 1,
      sym_STRING,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_DOT,
    STATE(42), 1,
      sym_classModification,
    STATE(55), 1,
      sym_modification,
    STATE(84), 1,
      sym_descriptionString,
    ACTIONS(103), 2,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [685] = 11,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(7), 1,
      anon_sym_within,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_withinClause,
    STATE(32), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [719] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(115), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_IDENT,
      sym_STRING,
  [734] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(119), 1,
      anon_sym_DOT,
    ACTIONS(117), 8,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
      anon_sym_end,
      anon_sym_extends,
      anon_sym_annotation,
      sym_IDENT,
  [751] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(121), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      sym_IDENT,
      sym_STRING,
  [766] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(123), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [780] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(125), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [794] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [822] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [850] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [878] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 1,
      anon_sym_block,
    ACTIONS(138), 1,
      anon_sym_class,
    ACTIONS(141), 1,
      anon_sym_model,
    ACTIONS(144), 1,
      anon_sym_package,
    STATE(28), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [906] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [934] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [962] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(151), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [976] = 9,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_class,
    ACTIONS(13), 1,
      anon_sym_model,
    ACTIONS(15), 1,
      anon_sym_package,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      aux_sym_storedDefinition_repeat1,
    STATE(62), 1,
      sym_classPrefixes,
    STATE(129), 1,
      sym_classDefinition,
  [1004] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(157), 1,
      anon_sym_PLUS,
    ACTIONS(155), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1020] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(159), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(161), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1048] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(163), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(165), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1076] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(167), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1090] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(169), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1104] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(171), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_for,
      anon_sym_RBRACE,
      anon_sym_annotation,
      sym_STRING,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(173), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1130] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(177), 1,
      anon_sym_EQ,
    ACTIONS(175), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1144] = 6,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(51), 1,
      sym_STRING,
    ACTIONS(107), 1,
      anon_sym_annotation,
    STATE(56), 1,
      sym_descriptionString,
    STATE(88), 1,
      sym_annotationClause,
    ACTIONS(179), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1164] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(181), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(183), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(185), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1199] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(187), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1210] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(189), 1,
      sym_IDENT,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_name,
    STATE(64), 2,
      sym__argument,
      sym_elementModification,
  [1227] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(193), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1238] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
  [1249] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
  [1260] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(199), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_annotation,
      sym_STRING,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(201), 5,
      ts_builtin_sym_end,
      anon_sym_block,
      anon_sym_class,
      anon_sym_model,
      anon_sym_package,
  [1282] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(189), 1,
      sym_IDENT,
    STATE(76), 1,
      sym_name,
    STATE(121), 1,
      sym_typeSpecifier,
  [1298] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(51), 1,
      sym_STRING,
    STATE(96), 1,
      sym_descriptionString,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1312] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(107), 1,
      anon_sym_annotation,
    STATE(95), 1,
      sym_annotationClause,
    ACTIONS(205), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1326] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(189), 1,
      sym_IDENT,
    STATE(18), 1,
      sym_name,
    STATE(93), 2,
      sym__argument,
      sym_elementModification,
  [1340] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(107), 1,
      anon_sym_annotation,
    STATE(90), 1,
      sym_annotationClause,
    ACTIONS(207), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1354] = 5,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_for,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_arrayConstructor_repeat1,
  [1370] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(111), 1,
      anon_sym_DOT,
    ACTIONS(215), 2,
      anon_sym_SEMI,
      sym_IDENT,
  [1381] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(219), 1,
      anon_sym_in,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1392] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(221), 1,
      sym_IDENT,
    STATE(128), 2,
      sym__classSpecifier,
      sym_longClassSpecifier,
  [1403] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_arrayConstructor_repeat2,
  [1416] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_classModification_repeat1,
  [1429] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_classModification_repeat1,
  [1442] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_arrayConstructor_repeat1,
  [1455] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(107), 1,
      anon_sym_annotation,
    ACTIONS(241), 1,
      anon_sym_end,
    STATE(108), 1,
      sym_annotationClause,
  [1468] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_componentClause_repeat1,
  [1481] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_componentClause_repeat1,
  [1494] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_arrayConstructor_repeat2,
  [1507] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    STATE(69), 1,
      aux_sym_componentClause_repeat1,
  [1520] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(107), 1,
      anon_sym_annotation,
    ACTIONS(259), 1,
      anon_sym_end,
    STATE(117), 1,
      sym_annotationClause,
  [1533] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_arrayConstructor_repeat2,
  [1546] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_classModification_repeat1,
  [1559] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(189), 1,
      sym_IDENT,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    STATE(89), 1,
      sym_name,
  [1572] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(111), 1,
      anon_sym_DOT,
    ACTIONS(267), 2,
      anon_sym_SEMI,
      sym_IDENT,
  [1583] = 4,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_arrayConstructor_repeat1,
  [1596] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(271), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1604] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(273), 1,
      sym_IDENT,
    STATE(82), 1,
      sym_forIndex,
  [1614] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(275), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1630] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1638] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(281), 1,
      sym_IDENT,
    STATE(68), 1,
      sym_componentDeclaration,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(283), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1656] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(273), 1,
      sym_IDENT,
    STATE(73), 1,
      sym_forIndex,
  [1666] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(78), 1,
      sym_classModification,
  [1676] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(189), 1,
      sym_IDENT,
    STATE(60), 1,
      sym_name,
  [1686] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(285), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1694] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(111), 1,
      anon_sym_DOT,
    ACTIONS(287), 1,
      anon_sym_SEMI,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(289), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1712] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(291), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1720] = 3,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(281), 1,
      sym_IDENT,
    STATE(91), 1,
      sym_componentDeclaration,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(293), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1738] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(295), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(297), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1754] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1762] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(301), 1,
      anon_sym_SEMI,
  [1769] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(303), 1,
      anon_sym_end,
  [1776] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(305), 1,
      anon_sym_SEMI,
  [1783] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(307), 1,
      anon_sym_end,
  [1790] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(309), 1,
      sym_IDENT,
  [1797] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(311), 1,
      anon_sym_SEMI,
  [1804] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(313), 1,
      sym_IDENT,
  [1811] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(315), 1,
      sym_IDENT,
  [1818] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(317), 1,
      anon_sym_SEMI,
  [1825] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(319), 1,
      sym_IDENT,
  [1832] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(321), 1,
      anon_sym_SEMI,
  [1839] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(323), 1,
      anon_sym_SEMI,
  [1846] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(325), 1,
      sym_IDENT,
  [1853] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(327), 1,
      anon_sym_end,
  [1860] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(329), 1,
      anon_sym_SEMI,
  [1867] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(331), 1,
      anon_sym_end,
  [1874] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(333), 1,
      sym_IDENT,
  [1881] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(335), 1,
      anon_sym_SEMI,
  [1888] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1895] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(339), 1,
      sym_IDENT,
  [1902] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(341), 1,
      anon_sym_SEMI,
  [1909] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(343), 1,
      sym_IDENT,
  [1916] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(345), 1,
      sym_STRING,
  [1923] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(347), 1,
      anon_sym_SEMI,
  [1930] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(349), 1,
      anon_sym_SEMI,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(351), 1,
      anon_sym_SEMI,
  [1944] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(353), 1,
      anon_sym_SEMI,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(355), 1,
      anon_sym_SEMI,
  [1958] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(357), 1,
      anon_sym_SEMI,
  [1965] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(359), 1,
      sym_IDENT,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(361), 1,
      sym_IDENT,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(363), 1,
      anon_sym_SEMI,
  [1986] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(365), 1,
      anon_sym_SEMI,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(367), 1,
      ts_builtin_sym_end,
  [2000] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(369), 1,
      sym_IDENT,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(371), 1,
      sym_IDENT,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_COMMENT,
    ACTIONS(373), 1,
      sym_IDENT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 160,
  [SMALL_STATE(6)] = 201,
  [SMALL_STATE(7)] = 242,
  [SMALL_STATE(8)] = 283,
  [SMALL_STATE(9)] = 321,
  [SMALL_STATE(10)] = 359,
  [SMALL_STATE(11)] = 419,
  [SMALL_STATE(12)] = 471,
  [SMALL_STATE(13)] = 523,
  [SMALL_STATE(14)] = 549,
  [SMALL_STATE(15)] = 575,
  [SMALL_STATE(16)] = 601,
  [SMALL_STATE(17)] = 622,
  [SMALL_STATE(18)] = 655,
  [SMALL_STATE(19)] = 685,
  [SMALL_STATE(20)] = 719,
  [SMALL_STATE(21)] = 734,
  [SMALL_STATE(22)] = 751,
  [SMALL_STATE(23)] = 766,
  [SMALL_STATE(24)] = 780,
  [SMALL_STATE(25)] = 794,
  [SMALL_STATE(26)] = 822,
  [SMALL_STATE(27)] = 850,
  [SMALL_STATE(28)] = 878,
  [SMALL_STATE(29)] = 906,
  [SMALL_STATE(30)] = 934,
  [SMALL_STATE(31)] = 962,
  [SMALL_STATE(32)] = 976,
  [SMALL_STATE(33)] = 1004,
  [SMALL_STATE(34)] = 1020,
  [SMALL_STATE(35)] = 1034,
  [SMALL_STATE(36)] = 1048,
  [SMALL_STATE(37)] = 1062,
  [SMALL_STATE(38)] = 1076,
  [SMALL_STATE(39)] = 1090,
  [SMALL_STATE(40)] = 1104,
  [SMALL_STATE(41)] = 1118,
  [SMALL_STATE(42)] = 1130,
  [SMALL_STATE(43)] = 1144,
  [SMALL_STATE(44)] = 1164,
  [SMALL_STATE(45)] = 1176,
  [SMALL_STATE(46)] = 1188,
  [SMALL_STATE(47)] = 1199,
  [SMALL_STATE(48)] = 1210,
  [SMALL_STATE(49)] = 1227,
  [SMALL_STATE(50)] = 1238,
  [SMALL_STATE(51)] = 1249,
  [SMALL_STATE(52)] = 1260,
  [SMALL_STATE(53)] = 1271,
  [SMALL_STATE(54)] = 1282,
  [SMALL_STATE(55)] = 1298,
  [SMALL_STATE(56)] = 1312,
  [SMALL_STATE(57)] = 1326,
  [SMALL_STATE(58)] = 1340,
  [SMALL_STATE(59)] = 1354,
  [SMALL_STATE(60)] = 1370,
  [SMALL_STATE(61)] = 1381,
  [SMALL_STATE(62)] = 1392,
  [SMALL_STATE(63)] = 1403,
  [SMALL_STATE(64)] = 1416,
  [SMALL_STATE(65)] = 1429,
  [SMALL_STATE(66)] = 1442,
  [SMALL_STATE(67)] = 1455,
  [SMALL_STATE(68)] = 1468,
  [SMALL_STATE(69)] = 1481,
  [SMALL_STATE(70)] = 1494,
  [SMALL_STATE(71)] = 1507,
  [SMALL_STATE(72)] = 1520,
  [SMALL_STATE(73)] = 1533,
  [SMALL_STATE(74)] = 1546,
  [SMALL_STATE(75)] = 1559,
  [SMALL_STATE(76)] = 1572,
  [SMALL_STATE(77)] = 1583,
  [SMALL_STATE(78)] = 1596,
  [SMALL_STATE(79)] = 1604,
  [SMALL_STATE(80)] = 1614,
  [SMALL_STATE(81)] = 1622,
  [SMALL_STATE(82)] = 1630,
  [SMALL_STATE(83)] = 1638,
  [SMALL_STATE(84)] = 1648,
  [SMALL_STATE(85)] = 1656,
  [SMALL_STATE(86)] = 1666,
  [SMALL_STATE(87)] = 1676,
  [SMALL_STATE(88)] = 1686,
  [SMALL_STATE(89)] = 1694,
  [SMALL_STATE(90)] = 1704,
  [SMALL_STATE(91)] = 1712,
  [SMALL_STATE(92)] = 1720,
  [SMALL_STATE(93)] = 1730,
  [SMALL_STATE(94)] = 1738,
  [SMALL_STATE(95)] = 1746,
  [SMALL_STATE(96)] = 1754,
  [SMALL_STATE(97)] = 1762,
  [SMALL_STATE(98)] = 1769,
  [SMALL_STATE(99)] = 1776,
  [SMALL_STATE(100)] = 1783,
  [SMALL_STATE(101)] = 1790,
  [SMALL_STATE(102)] = 1797,
  [SMALL_STATE(103)] = 1804,
  [SMALL_STATE(104)] = 1811,
  [SMALL_STATE(105)] = 1818,
  [SMALL_STATE(106)] = 1825,
  [SMALL_STATE(107)] = 1832,
  [SMALL_STATE(108)] = 1839,
  [SMALL_STATE(109)] = 1846,
  [SMALL_STATE(110)] = 1853,
  [SMALL_STATE(111)] = 1860,
  [SMALL_STATE(112)] = 1867,
  [SMALL_STATE(113)] = 1874,
  [SMALL_STATE(114)] = 1881,
  [SMALL_STATE(115)] = 1888,
  [SMALL_STATE(116)] = 1895,
  [SMALL_STATE(117)] = 1902,
  [SMALL_STATE(118)] = 1909,
  [SMALL_STATE(119)] = 1916,
  [SMALL_STATE(120)] = 1923,
  [SMALL_STATE(121)] = 1930,
  [SMALL_STATE(122)] = 1937,
  [SMALL_STATE(123)] = 1944,
  [SMALL_STATE(124)] = 1951,
  [SMALL_STATE(125)] = 1958,
  [SMALL_STATE(126)] = 1965,
  [SMALL_STATE(127)] = 1972,
  [SMALL_STATE(128)] = 1979,
  [SMALL_STATE(129)] = 1986,
  [SMALL_STATE(130)] = 1993,
  [SMALL_STATE(131)] = 2000,
  [SMALL_STATE(132)] = 2007,
  [SMALL_STATE(133)] = 2014,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(22),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(109),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(133),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(132),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(131),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(54),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 28), SHIFT_REPEAT(87),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elementList, 1, 0, 19),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_descriptionString_repeat1, 2, 0, 30),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_descriptionString_repeat1, 2, 0, 30),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_descriptionString_repeat1, 2, 0, 30), SHIFT_REPEAT(119),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_descriptionString, 2, 0, 25),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_descriptionString, 2, 0, 25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_descriptionString, 1, 0, 16),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_descriptionString, 1, 0, 16),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_descriptionString_repeat1, 2, 0, 29),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_descriptionString_repeat1, 2, 0, 29),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 1, 0, 7),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementModification, 1, 0, 18),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 3, 0, 20),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 26),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_elementList_repeat1, 2, 0, 26),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 7),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayConstructor, 3, 0, 58),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binaryExpression, 3, 0, 59),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 2, 0, 10),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 1, 0, 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 1, 0, 6),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 13),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 13), SHIFT_REPEAT(109),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 13), SHIFT_REPEAT(133),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 13), SHIFT_REPEAT(132),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 13), SHIFT_REPEAT(131),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 2, 0, 8),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 3, 0, 15),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryExpression, 2, 0, 54),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storedDefinition, 2, 0, 9),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayConstructor, 5, 0, 62),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayConstructor, 4, 0, 61),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logicalLiteral, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsignedRealLiteral, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsignedIntegerLiteral, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayConstructor, 6, 0, 65),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classModification, 3, 0, 38),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modification, 1, 0, 33),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 2, 0, 32),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classModification, 4, 0, 50),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classModification, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modification, 2, 0, 41),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modificationExpression, 1, 0, 42),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modificationExpression, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_withinClause, 3, 0, 14),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_withinClause, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modification, 3, 0, 56),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_storedDefinition_repeat1, 2, 0, 11),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementModification, 2, 0, 39),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 3, 0, 43),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 2, 0, 34),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeSpecifier, 2, 0, 23),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forIndex, 1, 0, 7),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_classModification_repeat1, 2, 0, 51), SHIFT_REPEAT(57),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_classModification_repeat1, 2, 0, 51),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat1, 2, 0, 28), SHIFT_REPEAT(6),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat1, 2, 0, 28),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentClause, 2, 0, 27),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_componentClause_repeat1, 2, 0, 47),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_componentClause_repeat1, 2, 0, 47), SHIFT_REPEAT(92),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat2, 2, 0, 66), SHIFT_REPEAT(79),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat2, 2, 0, 66),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentClause, 3, 0, 36),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeSpecifier, 1, 0, 18),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotationClause, 2, 0, 24),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat1, 2, 0, 58),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_forIndex, 3, 0, 63),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayConstructor_repeat2, 2, 0, 64),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementModification, 2, 0, 40),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 3, 0, 44),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 3, 0, 45),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_componentClause_repeat1, 2, 0, 46),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_classModification_repeat1, 2, 0, 38),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 2, 0, 35),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_componentDeclaration, 4, 0, 55),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elementModification, 3, 0, 52),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 5, 0, 48),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 5, 0, 49),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 4, 0, 37),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 6, 0, 53),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classPrefixes, 1, 0, 1),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 4, 0, 31),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 6, 0, 57),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 7, 0, 60),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extendsClause, 2, 0, 22),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_longClassSpecifier, 3, 0, 21),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namedElement, 1, 0, 17),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namedElement, 1, 0, 11),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classDefinition, 2, 0, 12),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [367] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classPrefixes, 1, 0, 4),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classPrefixes, 1, 0, 3),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classPrefixes, 1, 0, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_modelica36(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_IDENT,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
